### ISSUE TITLE
HP bar rendering in front of action bar

### ISSUE THREAD

**Issue by Chocolate06** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#14]
![HP Bar forefront](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/132630165/469bdf01-811a-4e66-b7f4-3a537f81650b)

**Comment by Meruheart** [comment]
Still happens

**Comment by LordMonoxide** [comment]
In main repo already
