### ISSUE TITLE
Overall Pixelation

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#18]
**Describe the bug**
Noticed some strange pixels in the sky here, but then I realized that SC is much more pixelated than retail pretty much everywhere. This might be just my graphics settings, I'm using 8K in windowed.

![SC Strange Pixels in the Sky](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/2b30a334-df11-474c-9ce6-1a3ca2f2bf63)
![Retail Clear Skies](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/2b523c31-e1bc-4258-834a-e437035d66a2)

**Comment by Zychronix** [comment]
This is just SC with no filtering vs an emulator with filtering on.
See below how it looks on an emulator with no filtering.
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/14896608/174b1090-5968-4c66-82ad-4b7b3cdb8236)

**Comment by Wulves** [comment]
Ah I gotcha, here I was thinking it might be due to widescreen or something. I'll close this one then since it's not a bug. Thanks for letting me know <3
