### ISSUE TITLE
Text Box in Nelos' House during Fade Out

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#19]
**Describe the bug**
The text box in Nello's house highlights the background in blue during fade out which stands out as odd, and as the screen darkens completely the box appears as solid black instead of as normal. Screenshot is from retail with how it normally looks.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/a4e82f53-2ab0-49f7-b310-c8469dd4f77a

![Retail Nelos House](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/91bca550-21a1-46b9-b3fa-97e0749f4d3d)

**Comment by Wulves** [comment]
Identical issues spotted during these two cutscenes- looks like the window pane is being affected by screen fade effects in general. The text box is black when Wink yells, and the text box for Kate's dialogue is visually dimmed during the flash back.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/319739d2-0481-44ab-88d8-abbf93be9213

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/e45054b4-8670-4351-9991-60404f748a22

**Comment by LordMonoxide** [comment]
Resolved
