### ISSUE TITLE
Cutscene Audio Stuttering Hard

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#23]
**Describe the bug**
First cutscene from Fester talking about the MTNS and the Black Whatchamacallit had audio stutter.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/f7ebc748-78fa-44b2-acf0-e6975ee477f0

**Comment by Wulves** [comment]
Also occurs for the ghost ship cutscene

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/0f328266-d2e7-4746-9b55-21131a99e6a4

**Comment by LordMonoxide** [comment]
Resolved
