### ISSUE TITLE
Dart's Invisible Soles

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#25]
**Describe the bug**
I know this is a known bug in disc 3, but figured I'd post it here since I spotted it in disc 2. When running around, the bottom of Dart's feet are invisible.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/d662f22f-f72b-46ef-9ad0-24402b676b73

**Comment by LordMonoxide** [comment]
Logged in main repo, this is one of Dart's low quality models and it just doesn't have soles
