### ISSUE TITLE
Dart Vibrations

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#26]
**Describe the bug**
When running into an npc, usually Dart just stops and rotates slightly in place based on where you have your thumbstick pointing. Noticed when running into one in SC that sometimes Dart is a bit excited to talk to people and vibrates. This is kind of a super minor nit picky thing, which I'm not 100% sure qualifies as a bug.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/b9fb0943-02a4-4e13-9465-dfcc173d71de

**Comment by LordMonoxide** [comment]
Resolved
