### ISSUE TITLE
Pre-menu Audio Stutter

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#27]
**Describe the bug**
Occurs worse when the game is launched for the first time after rebooting my pc, but the pre-menu cutscene experiences some audio stutter just at the start.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/b74be6f2-98ad-4def-8521-9b8f7bee2ccd

**Comment by LordMonoxide** [comment]
Resolved
