### ISSUE TITLE
Bandits Clipping in Cutscene

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#28]
**Describe the bug**
The bandits move through the black bars at the top and bottom of the screen, and the top bandit also appears to be over the archway instead of under it.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/e5d2071a-5cfa-4299-bb0b-286e21acb19a

**Comment by theflyingzamboni** [comment]
This is what it looks like in retail. Mostly likely due to designing for CRT overscan, so this wasn't visible on the screens the devs were testing on.
