### ISSUE TITLE
Combat Animation Not Playing

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#31]
**Describe the bug**
Instead of the usual animation the display sort of just, shrinks to a line and then vanishes. I remember someone else having this issue in the testing chat, but there's no ticket for it so I thought I'd open one here.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/5b6dd44e-930d-4925-809a-a81d3ff2a061

**Comment by Wulves** [comment]
Just noticed thanks to another clip of this, but the image isn't actually shrinking, it's being turned until the edge is parallel to the viewer- making it seem like it's vanishing. No clue if that knowledge will help patching it, but thought I'd mention it

**Comment by LordMonoxide** [comment]
Resolved
