### ISSUE TITLE
Successful Counter Sounds Off

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#34]
**Describe the bug**
When successfully countering during additions, the last sound played sounds odd to me. Not sure how better to describe it than that. For the clip the sound plays between seconds 4 and 5.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/a7ae4567-ff39-4d11-af41-e711a35bbb90

**Comment by Wulves** [comment]
Found a more obviously odd moment from later in my playthrough

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/afe13647-df44-4da9-b3a6-cba21603806b

**Comment by LordMonoxide** [comment]
Resolved
