### ISSUE TITLE
Save Point Discrepancy

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#35]
**Describe the bug**
In retail there are about 6 faint save point lights which move about slowly. In SC there are 3 bright save point lights that zoom quickly.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/55715e0e-550c-47f4-ba68-083455de731d

**Comment by LordMonoxide** [comment]
Resolved
