### ISSUE TITLE
Magic Stone of Signet Discrepancy

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#36]
**Describe the bug**
In retail using this on an enemy highlights them in a dark glow, which is absent in SC.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/f43b88e4-03b2-4e29-ba26-024bcff16812

**Comment by LordMonoxide** [comment]
Resolved
