### ISSUE TITLE
Heat Blade does not apply twinkle effect when attacking a Water element enemy

### ISSUE THREAD

**Issue by garrettgm** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#37]
**Describe the bug**
Heat Blade does not apply twinkle effect when attacking a Water element enemy

**To Reproduce**
1. Equip Dart with a Heat Blade
2. Begin a combat encounter with a water enemy (F12, Encounter id 36 Merman)
3. Attack the enemy with Dart
4. Observe that the attack has only the normal attack effects

**Expected behavior**
The attack with a Heat Blade should have a red twinkle effect to it when attacking a Water element enemy.

**Comment by Chocolate06** [comment]
I believe this might be all weapon trails, noticable on Twister Glaive against Kongol

**Comment by LordMonoxide** [comment]
Resolved
