### ISSUE TITLE
Virage Stuttering Confusion Attack

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#42]
**Describe the bug**
Virage model appears to revert to 30 fps or otherwise is stuttering during its confusion attack.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/4e8488f7-319a-4df0-928b-aba461322e3c

**Comment by LordMonoxide** [comment]
Resolved
