### ISSUE TITLE
Virage Damage Numbers Misaligned

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#43]
**Describe the bug**
When attacking the head with an addition the damage numbers veer off to the left instead of straight up.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/55959e8b-5be0-42ce-817f-81c9f4f480dc

**Comment by Wulves** [comment]
Also when attacking the body the numbers are misaligned to the right

**Comment by Wulves** [comment]
Regole's damage numbers are also misaligned

**Comment by LordMonoxide** [comment]
Already reported in main repo
