### ISSUE TITLE
Virage Cutscene Multiple Issues

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#44]
**Describe the bug**
Shana has a 2D square above her head for the whole cutscene. Heard some audio pop/crackling and also the sound the virage makes when reaching out seems slightly different from retail like it's pitched up maybe.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/81803aa8-1da2-4073-aaea-c80e5d958106

**Comment by Wulves** [comment]
Shana seems determined to out herself as the soul of the god of destruction with this bootleg halo because it's in later cutscenes too

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/be1a744d-d9bb-4b66-a54a-eddb012b2ef0

**Comment by LordMonoxide** [comment]
Resolved
