### ISSUE TITLE
Bandit Eye-Patch Flip

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#45]
**Describe the bug**
I doubt anyone would notice on native resolution so I'm not sure if this is in retail, but I noticed with the far clearer models in SC that for some reason when the bandits move, their eye patch mysteriously switches to their other eye. I'm thinking this might be that the cheer animation and the one where they just have their sword out are different.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/79a5afe2-aea1-49f0-88aa-ea0cc47a24ee

**Comment by LordMonoxide** [comment]
Hilarious, but not worth fixing
