### ISSUE TITLE
Haschel's Choppy Dragoon Transformation

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#49]
**Describe the bug**
Haschel's dragoon animation is incredibly choppy at the start

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/c610a3c1-0cdf-466f-9c3f-b1a3a4ad1634

**Comment by LordMonoxide** [comment]
Resolved
