### ISSUE TITLE
Picking up a Key Item Gave Wrong Sound

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#53]
**Describe the bug**
Sidenote: in retail Dart interacting with the Giganto chair doesn't make a noise, but it does in SC. Not sure if this is a bug or restoring a broken feature in retail. 

Audio that plays when picking up Dart's Dragoon spirit is awesome- but not the usual one found in retail.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/b7f733ea-f8f9-45f8-8db3-430bd210f18b

**Comment by Wulves** [comment]
Later on, the sound was played correctly, so it appears to be an inconsistent issue.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/65aacdff-2d8d-42f7-b1d7-67150e28fa0b

**Comment by LordMonoxide** [comment]
Resolved
