### ISSUE TITLE
Valley of CG Stone Interaction Audio Oddities

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#54]
**Describe the bug**
These appear to occur when you press to interact almost simultaneously to when the prompt appears, which cuts off the first sound of the prompt appearing. Sometimes this made only one audio note play instead of the two that should. Also when descending the tree the audio was like two notes but neither finished.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/ee3bae19-6b90-4e6b-9707-1f7c2bfff41f

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/d52c9d6b-c115-4f86-9d7f-9f2c8dc6afe9

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/29c8cc3d-93b1-4de0-9062-508fdf75963f

**Comment by Wulves** [comment]
Looks like the issue may persist across all intractables, as it's definitely present here.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/a5ca3402-21e7-4611-b0a4-7bf383e6db43

**Comment by Wulves** [comment]
If it helps, the sound also sometimes just doesn't even play

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/179f25a4-7aa2-4178-9225-c4e624ffb7bc

**Comment by LordMonoxide** [comment]
Resolved
