### ISSUE TITLE
Virage 2 missing HP bars

### ISSUE THREAD

**Issue by Chocolate06** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#60]
Similar to Virage 1, only the head has an HP bar

![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/132630165/012346a1-ba89-4b9a-81cd-ea18b0cc98d7)

**Comment by LordMonoxide** [comment]
Merging with other issue
