### ISSUE TITLE
Emperor Doel Attack Stutter

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#7]
**Describe the bug**
This specific attack in the video seems to be at a lower fps or something compared to how smooth everything else was. It was consistently only this attack as well.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/f4c33985-e2a9-4701-b681-6a4be25b10c1

**Comment by LordMonoxide** [comment]
Resolved
