### ISSUE TITLE
Background Ghost Flames are Transparent

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#70]
**Describe the bug**
Ghost flames are meant to be fully colored and not transparent here.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/e44a6855-9f87-4c4a-aaf8-65614705e15f

**Comment by DrewUniverse** [comment]
They do seem to be brighter / fuller in retail. However, a point of clarity that they still had some transparency in retail. 
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/70291675/1caeb42b-8e4a-4ed7-94ef-15a62150893c)

**Comment by LordMonoxide** [comment]
Excessive transparency has been resolved
