### ISSUE TITLE
Screen doesn't go completely black while resting on Queen Fury

### ISSUE THREAD

**Issue by Chocolate06** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#71]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/132630165/855770e4-f24a-49aa-9afe-b50a73410e73

**Comment by Wulves** [comment]
Can confirm I experienced the same issue. I believe there's an issue with fade outs in general.

**Comment by LordMonoxide** [comment]
Resolved
