### ISSUE TITLE
Generic Foe Magic Animation is Dim

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#78]
**Describe the bug**
The orb is far more dim in SC than in retail

SC

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/5492fcc8-498b-4695-9988-7a3bdfbaee23

Retail

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/d5771203-b49a-413c-b8d9-e4c7e036b4cd

![Difference](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/fcb9da86-f606-4da1-981c-7b0697b9d717)

**Comment by LordMonoxide** [comment]
Resolved
