### ISSUE TITLE
Elevator chains glitch (sometimes) [Warp ID 25,26]

### ISSUE THREAD

**Issue by Ehko4** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#87]
**Describe the bug**
As the elevators lower and raise, the chain begins to glitch. Sometimes, its during the initial lowering, other times its only after using speedup. Kind of difficult to reproduce on purpose, it feels kind of random. Happens more when using speedup, sometimes it will linger after using.

In Submap 25, the chain goes behind the flames in the brazier. 

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170750797/0fb3bd6d-9bca-45c3-9e39-44e4062e4e8f

**To Reproduce**
1. Go to Submaps 25 and/or 26
2. Hang around or jump back and forth between areas (less likely to happen)
3. Use "+/=" to speedup (more likely to happen)
4. See error in the elevator chains

**Expected behavior**
Pretty lifting chains

**Comment by LordMonoxide** [comment]
Resolved
