### ISSUE TITLE
Weird NPC Texture in the Disc 2 Starting Cutscene

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#9]
**Describe the bug**
The person in the far back has a T shaped splice in their texture. I know that the other npcs whose heads are floating off their bodies are retail, but figured I'd point that out too since it seems like something that could be improved over the retail version.

![SC Floating Heads](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/2a903071-c9a3-4946-979b-7ef6879911c7)

**Comment by LordMonoxide** [comment]
This is one of the 2D cross-shaped NPCs
