### ISSUE TITLE
World Map names are blue unless they are story target

### ISSUE THREAD

**Issue by Ehko4** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#90]
**Describe the bug**
While at the world map, if you hit start to display the names of locations, all the names other than your next story target appear blue instead of white.

**To Reproduce**
1. Go to World Map
2. Click on 'Start'
3. If you're close enough or can turn the screen to see next target, you'll be able to discern the difference.

Photo only shows North, but it happens in South as well.

![java_tlLBN0vpTC](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170750797/f8536434-d9ef-4af3-818a-a9b7902f71ac)

**Comment by LordMonoxide** [comment]
Resolved
