### ISSUE TITLE
When Entering Local -  Incorrect text

### ISSUE THREAD

**Issue by Ehko4** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#91]
**Describe the bug**
When trying to enter any location, the text is incorrect for saying you don't want to enter. "Don't enter" instead of "No Entry".

**To Reproduce**
It's there when attempting to enter (or accidentally running into) each location.

![duckstation-qt-x64-ReleaseLTCG_Fr7a4dLFRC](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170750797/1be8fac5-abfc-4f82-ba1f-47fd217fb2b9)

Expected: "No Entry"

**Comment by LordMonoxide** [comment]
This was an intentional change to improve awkward translations
